[package]
name = "weather-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weather_library = { path = "/Users/ganesholi/Developer/rust-practice/weather-app/weather_library" }